version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
    environment:
      - TZ=Europe/Moscow
    networks:
      - fitness_network

networks:
  fitness_network:
    driver: bridge